# Generated by Django 6.0.1 on 2026-01-23 19:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('type_bourse', models.CharField(choices=[('TOTALE', 'Bourse totale (100%)'), ('PARTIELLE', 'Bourse partielle (%)'), ('MONTANT_FIXE', 'Montant fixe')], help_text='Type de bourse', max_length=20)),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de réduction (si bourse partielle, 0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('montant_fixe', models.DecimalField(blank=True, decimal_places=2, help_text='Montant fixe de la bourse (en FCFA)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('source_financement', models.CharField(choices=[('GOUVERNEMENT', 'Gouvernement'), ('UNIVERSITE', 'Université'), ('ENTREPRISE', 'Entreprise privée'), ('ONG', 'ONG'), ('AUTRE', 'Autre')], help_text='Source de financement de la bourse', max_length=20)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='EN_COURS', help_text='Statut actuel de la bourse', max_length=20)),
                ('date_debut', models.DateField(help_text='Date de début de la bourse')),
                ('date_fin', models.DateField(help_text='Date de fin de la bourse')),
                ('nom_organisme', models.CharField(blank=True, help_text="Nom de l'organisme financeur", max_length=200)),
                ('reference_decision', models.CharField(blank=True, help_text="Référence de la décision d'attribution", max_length=100)),
                ('conditions', models.TextField(blank=True, help_text='Conditions de maintien de la bourse')),
                ('observations', models.TextField(blank=True, help_text='Observations diverses')),
                ('annee_academique', models.ForeignKey(help_text='Année académique concernée', on_delete=django.db.models.deletion.PROTECT, related_name='bourses', to='academic.anneeacademique')),
                ('etudiant', models.ForeignKey(help_text='Étudiant bénéficiaire', on_delete=django.db.models.deletion.CASCADE, related_name='bourses', to='students.etudiant')),
            ],
            options={
                'verbose_name': 'Bourse',
                'verbose_name_plural': 'Bourses',
                'db_table': 'bourses',
                'ordering': ['-date_debut'],
                'indexes': [models.Index(fields=['etudiant', 'annee_academique'], name='bourses_etudian_b03273_idx'), models.Index(fields=['statut'], name='bourses_statut_6106aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('numero_facture', models.CharField(help_text='Numéro unique de la facture (généré automatiquement)', max_length=50, unique=True)),
                ('montant_brut', models.DecimalField(decimal_places=2, help_text='Montant total des frais de scolarité (avant réductions)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant_reduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total des réductions (bourses, exonérations)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant_net', models.DecimalField(decimal_places=2, help_text='Montant net à payer (brut - réductions)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('montant_paye', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant total déjà payé', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('solde', models.DecimalField(decimal_places=2, help_text='Solde restant à payer (net - payé)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_emission', models.DateField(auto_now_add=True, help_text='Date de génération de la facture')),
                ('date_echeance', models.DateField(help_text='Date limite de paiement')),
                ('statut', models.CharField(choices=[('IMPAYEE', 'Impayée'), ('PARTIELLE', 'Partiellement payée'), ('SOLDEE', 'Soldée'), ('ANNULEE', 'Annulée')], default='IMPAYEE', help_text='Statut actuel de la facture', max_length=20)),
                ('observations', models.TextField(blank=True, help_text='Observations sur la facture')),
                ('inscription', models.OneToOneField(help_text='Inscription concernée', on_delete=django.db.models.deletion.PROTECT, related_name='facture', to='students.inscription')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'factures',
                'ordering': ['-date_emission'],
                'indexes': [models.Index(fields=['numero_facture'], name='factures_numero__26e278_idx'), models.Index(fields=['statut'], name='factures_statut_d839a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='FraisScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('niveau', models.CharField(help_text="Niveau d'études (ex: L1, L2, L3, M1, M2)", max_length=10)),
                ('montant_total', models.DecimalField(decimal_places=2, help_text='Montant total des frais de scolarité (en FCFA)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('nombre_tranches', models.PositiveIntegerField(default=1, help_text='Nombre de tranches de paiement autorisées (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('date_limite_paiement', models.DateField(help_text='Date limite pour le paiement complet')),
                ('actif', models.BooleanField(default=True, help_text="True si ces frais sont actifs pour l'année en cours")),
                ('description', models.TextField(blank=True, help_text='Description détaillée des frais (inclus/exclus)')),
                ('annee_academique', models.ForeignKey(help_text='Année académique concernée', on_delete=django.db.models.deletion.PROTECT, related_name='frais_scolarite', to='academic.anneeacademique')),
                ('filiere', models.ForeignKey(help_text='Filière concernée', on_delete=django.db.models.deletion.PROTECT, related_name='frais_scolarite', to='academic.filiere')),
            ],
            options={
                'verbose_name': 'Frais de scolarité',
                'verbose_name_plural': 'Frais de scolarité',
                'db_table': 'frais_scolarite',
                'ordering': ['-annee_academique', 'filiere', 'niveau'],
                'indexes': [models.Index(fields=['filiere', 'annee_academique'], name='frais_scola_filiere_bd3cea_idx'), models.Index(fields=['actif'], name='frais_scola_actif_f126a2_idx')],
                'unique_together': {('filiere', 'annee_academique', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant payé (en FCFA)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money'), ('CHEQUE', 'Chèque'), ('AUTRE', 'Autre')], help_text='Mode de paiement utilisé', max_length=20)),
                ('date_paiement', models.DateField(help_text='Date à laquelle le paiement a été effectué')),
                ('numero_recu', models.CharField(help_text='Numéro unique du reçu de paiement (généré automatiquement)', max_length=50, unique=True)),
                ('reference_transaction', models.CharField(blank=True, help_text='Référence de la transaction (virement, mobile money, chèque)', max_length=100)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', help_text='Statut actuel du paiement', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date et heure de validation', null=True)),
                ('observations', models.TextField(blank=True, help_text='Observations sur le paiement')),
                ('inscription', models.ForeignKey(help_text='Inscription concernée (étudiant + année académique)', on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='students.inscription')),
                ('valide_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a validé le paiement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-date_paiement'],
                'indexes': [models.Index(fields=['numero_recu'], name='paiements_numero__4dab31_idx'), models.Index(fields=['statut'], name='paiements_statut_ce5cce_idx'), models.Index(fields=['date_paiement'], name='paiements_date_pa_250ef0_idx')],
            },
        ),
    ]
