# Generated by Django 6.0.1 on 2026-01-24 10:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('nom', models.CharField(help_text="Nom de l'équipement", max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'équipement")),
                ('reference', models.CharField(help_text="Référence unique de l'équipement (code-barres, numéro série)", max_length=100, unique=True)),
                ('categorie', models.CharField(choices=[('INFORMATIQUE', 'Informatique'), ('AUDIOVISUEL', 'Audiovisuel'), ('MOBILIER', 'Mobilier'), ('SPORTIF', 'Sportif'), ('SCIENTIFIQUE', 'Scientifique'), ('AUTRE', 'Autre')], help_text="Catégorie de l'équipement", max_length=20)),
                ('etat', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVE', 'Réservé'), ('EN_MAINTENANCE', 'En maintenance'), ('HORS_SERVICE', 'Hors service')], default='DISPONIBLE', help_text="État actuel de l'équipement", max_length=20)),
                ('quantite_disponible', models.PositiveIntegerField(default=1, help_text='Quantité disponible en stock', validators=[django.core.validators.MinValueValidator(0)])),
                ('quantite_totale', models.PositiveIntegerField(default=1, help_text='Quantité totale (disponible + réservée + en maintenance)', validators=[django.core.validators.MinValueValidator(1)])),
                ('date_acquisition', models.DateField(blank=True, help_text="Date d'achat de l'équipement", null=True)),
                ('valeur_acquisition', models.DecimalField(blank=True, decimal_places=2, help_text="Valeur d'achat (en FCFA)", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dernier_entretien', models.DateField(blank=True, help_text='Date du dernier entretien/maintenance', null=True)),
                ('prochain_entretien', models.DateField(blank=True, help_text='Date du prochain entretien prévu', null=True)),
                ('reservable', models.BooleanField(default=True, help_text="True si l'équipement peut être réservé")),
                ('observations', models.TextField(blank=True, help_text='Observations diverses')),
                ('salle', models.ForeignKey(blank=True, help_text="Salle où se trouve l'équipement (emplacement par défaut)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipements_inventaire', to='schedule.salle')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'db_table': 'equipements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('type_maintenance', models.CharField(choices=[('PREVENTIVE', 'Préventive'), ('CORRECTIVE', 'Corrective'), ('URGENTE', 'Urgente')], help_text='Type de maintenance', max_length=20)),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', help_text='Statut actuel de la maintenance', max_length=20)),
                ('date_planifiee', models.DateField(help_text='Date planifiée pour la maintenance')),
                ('date_debut', models.DateTimeField(blank=True, help_text='Date et heure de début effectif', null=True)),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date et heure de fin', null=True)),
                ('description', models.TextField(help_text='Description de la maintenance/panne')),
                ('travaux_effectues', models.TextField(blank=True, help_text='Description des travaux effectués')),
                ('pieces_remplacees', models.TextField(blank=True, help_text='Liste des pièces remplacées')),
                ('cout_main_oeuvre', models.DecimalField(blank=True, decimal_places=2, help_text="Coût de la main d'œuvre (en FCFA)", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cout_pieces', models.DecimalField(blank=True, decimal_places=2, help_text='Coût des pièces (en FCFA)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observations', models.TextField(blank=True, help_text='Observations diverses')),
                ('equipement', models.ForeignKey(help_text='Équipement concerné par la maintenance', on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='resources.equipement')),
                ('technicien', models.ForeignKey(blank=True, help_text='Technicien assigné à la maintenance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenances_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'db_table': 'maintenances',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('type_reservation', models.CharField(choices=[('SALLE', 'Salle'), ('EQUIPEMENT', 'Équipement'), ('SALLE_EQUIPEMENT', 'Salle + Équipement')], help_text='Type de réservation', max_length=20)),
                ('date_debut', models.DateTimeField(help_text='Date et heure de début de la réservation')),
                ('date_fin', models.DateTimeField(help_text='Date et heure de fin de la réservation')),
                ('motif', models.CharField(help_text='Motif de la réservation (ex: réunion, cours, événement)', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Description détaillée de l'activité prévue")),
                ('nombre_participants', models.PositiveIntegerField(blank=True, help_text='Nombre de participants attendus', null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REJETEE', 'Rejetée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', help_text='Statut actuel de la réservation', max_length=20)),
                ('date_validation', models.DateTimeField(blank=True, help_text='Date et heure de validation/rejet', null=True)),
                ('commentaire_validation', models.TextField(blank=True, help_text='Commentaire lors de la validation/rejet')),
                ('demandeur', models.ForeignKey(help_text='Utilisateur qui fait la demande de réservation', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('salle', models.ForeignKey(blank=True, help_text='Salle réservée (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='schedule.salle')),
                ('valide_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a validé/rejeté la réservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'db_table': 'reservations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEquipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('quantite', models.PositiveIntegerField(default=1, help_text='Quantité réservée', validators=[django.core.validators.MinValueValidator(1)])),
                ('retourne', models.BooleanField(default=False, help_text="True si l'équipement a été retourné")),
                ('date_retour', models.DateTimeField(blank=True, help_text='Date et heure du retour', null=True)),
                ('etat_retour', models.TextField(blank=True, help_text="État de l'équipement au retour")),
                ('equipement', models.ForeignKey(help_text='Équipement réservé', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='resources.equipement')),
                ('reservation', models.ForeignKey(help_text='Réservation concernée', on_delete=django.db.models.deletion.CASCADE, related_name='equipements_reserves', to='resources.reservation')),
            ],
            options={
                'verbose_name': "Réservation d'équipement",
                'verbose_name_plural': "Réservations d'équipements",
                'db_table': 'reservations_equipements',
                'ordering': ['reservation', 'equipement'],
            },
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['reference'], name='equipements_referen_09b3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['categorie'], name='equipements_categor_647995_idx'),
        ),
        migrations.AddIndex(
            model_name='equipement',
            index=models.Index(fields=['etat'], name='equipements_etat_2d10ab_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['equipement', 'date_planifiee'], name='maintenance_equipem_6aa833_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['type_maintenance'], name='maintenance_type_ma_32794c_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenance',
            index=models.Index(fields=['statut'], name='maintenance_statut_ae655f_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['demandeur'], name='reservation_demande_325fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['salle', 'date_debut'], name='reservation_salle_i_d5bb4a_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['statut'], name='reservation_statut_d20d98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reservationequipement',
            unique_together={('reservation', 'equipement')},
        ),
    ]
