# Generated by Django 6.0.1 on 2026-01-24 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('notif_notes', models.BooleanField(default=True, help_text='Activer les notifications de nouvelles notes')),
                ('notif_absences', models.BooleanField(default=True, help_text="Activer les notifications d'absences")),
                ('notif_paiements', models.BooleanField(default=True, help_text='Activer les notifications de paiements')),
                ('notif_bibliotheque', models.BooleanField(default=True, help_text='Activer les notifications de bibliothèque (retours)')),
                ('notif_emploi_temps', models.BooleanField(default=True, help_text="Activer les notifications d'emploi du temps")),
                ('notif_annonces', models.BooleanField(default=True, help_text="Activer les notifications d'annonces")),
                ('notif_messages', models.BooleanField(default=True, help_text='Activer les notifications de nouveaux messages')),
                ('activer_email', models.BooleanField(default=True, help_text='Activer les notifications par email')),
                ('activer_sms', models.BooleanField(default=False, help_text='Activer les notifications par SMS')),
                ('activer_push', models.BooleanField(default=True, help_text='Activer les notifications push (application)')),
                ('frequence_digest', models.CharField(choices=[('IMMEDIAT', 'Immédiat'), ('QUOTIDIEN', 'Digest quotidien'), ('HEBDOMADAIRE', 'Digest hebdomadaire')], default='IMMEDIAT', help_text="Fréquence d'envoi des notifications par email", max_length=20)),
                ('utilisateur', models.OneToOneField(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='preference_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de notification',
                'verbose_name_plural': 'Préférences de notification',
                'db_table': 'preferences_notification',
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('titre', models.CharField(help_text="Titre de l'annonce", max_length=200)),
                ('contenu', models.TextField(help_text="Contenu complet de l'annonce")),
                ('type_annonce', models.CharField(choices=[('GENERALE', 'Générale'), ('ETUDIANTS', 'Étudiants'), ('ENSEIGNANTS', 'Enseignants'), ('ADMINISTRATION', 'Administration'), ('URGENTE', 'Urgente')], default='GENERALE', help_text="Public cible de l'annonce", max_length=20)),
                ('est_prioritaire', models.BooleanField(default=False, help_text="True si l'annonce doit être mise en avant")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('ARCHIVEE', 'Archivée')], default='BROUILLON', help_text='Statut de publication', max_length=20)),
                ('date_publication', models.DateTimeField(blank=True, help_text='Date et heure de publication', null=True)),
                ('date_expiration', models.DateTimeField(blank=True, help_text="Date d'expiration de l'annonce (optionnel)", null=True)),
                ('piece_jointe', models.FileField(blank=True, help_text="Document joint à l'annonce (PDF, image, etc.)", null=True, upload_to='annonces/%Y/%m/')),
                ('auteur', models.ForeignKey(help_text="Utilisateur qui a créé l'annonce", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'db_table': 'annonces',
                'ordering': ['-date_publication', '-created_at'],
                'indexes': [models.Index(fields=['type_annonce'], name='annonces_type_an_7fe14d_idx'), models.Index(fields=['statut'], name='annonces_statut_2b052e_idx'), models.Index(fields=['date_publication'], name='annonces_date_pu_470a32_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('sujet', models.CharField(help_text='Sujet du message', max_length=200)),
                ('corps', models.TextField(help_text='Corps du message')),
                ('piece_jointe', models.FileField(blank=True, help_text='Document joint au message', null=True, upload_to='messages/%Y/%m/')),
                ('est_lu', models.BooleanField(default=False, help_text='True si le message a été lu par le destinataire')),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Date et heure de lecture', null=True)),
                ('est_archive', models.BooleanField(default=False, help_text='True si le message est archivé')),
                ('destinataire', models.ForeignKey(help_text='Utilisateur qui reçoit le message', on_delete=django.db.models.deletion.CASCADE, related_name='messages_recus', to=settings.AUTH_USER_MODEL)),
                ('expediteur', models.ForeignKey(help_text='Utilisateur qui a envoyé le message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL)),
                ('message_parent', models.ForeignKey(blank=True, help_text="Message parent (si c'est une réponse)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to='communications.message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['expediteur', 'destinataire'], name='messages_expedit_0356ca_idx'), models.Index(fields=['destinataire', 'est_lu'], name='messages_destina_842f0b_idx'), models.Index(fields=['message_parent'], name='messages_message_c459da_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('titre', models.CharField(help_text='Titre court de la notification', max_length=200)),
                ('message', models.TextField(help_text='Message complet de la notification')),
                ('type_notification', models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('ALERTE', 'Alerte'), ('ERREUR', 'Erreur')], default='INFO', help_text='Type de notification', max_length=20)),
                ('canal', models.CharField(choices=[('APP', 'Application'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='APP', help_text='Canal de diffusion', max_length=20)),
                ('est_lue', models.BooleanField(default=False, help_text='True si la notification a été lue')),
                ('date_lecture', models.DateTimeField(blank=True, help_text='Date et heure de lecture', null=True)),
                ('lien', models.CharField(blank=True, help_text='URL de redirection (optionnel)', max_length=500)),
                ('envoyee', models.BooleanField(default=False, help_text='True si la notification a été envoyée')),
                ('date_envoi', models.DateTimeField(blank=True, help_text="Date et heure d'envoi", null=True)),
                ('destinataire', models.ForeignKey(help_text='Utilisateur destinataire de la notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['destinataire', 'est_lue'], name='notificatio_destina_429d8b_idx'), models.Index(fields=['type_notification'], name='notificatio_type_no_11e5ed_idx'), models.Index(fields=['canal'], name='notificatio_canal_ae2c8b_idx')],
            },
        ),
    ]
