# Generated by Django 6.0.1 on 2026-01-17 22:20

import apps.students.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Ex: ENS2024001', max_length=20, unique=True, verbose_name='Matricule')),
                ('specialite', models.CharField(help_text='Ex: Bases de données, Intelligence Artificielle', max_length=200, verbose_name='Spécialité')),
                ('grade', models.CharField(choices=[('ASSISTANT', 'Assistant'), ('CHARGE_COURS', 'Chargé de cours'), ('MAITRE_ASSISTANT', 'Maître Assistant'), ('MAITRE_CONFERENCES', 'Maître de Conférences'), ('PROFESSEUR', 'Professeur')], max_length=30, verbose_name='Grade')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email_personnel', models.EmailField(max_length=254, verbose_name='Email personnel')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.students.models.enseignant_photo_path, verbose_name='Photo')),
                ('cv', models.FileField(blank=True, help_text='Curriculum Vitae', null=True, upload_to=apps.students.models.enseignant_cv_path, verbose_name='CV (PDF)')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EN_CONGE', 'En congé'), ('RETIRE', 'Retraité')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='academic.departement', verbose_name='Département')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'db_table': 'students_enseignants',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Ex: ETU2024001', max_length=20, unique=True, verbose_name='Matricule')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('lieu_naissance', models.CharField(max_length=200, verbose_name='Lieu de naissance')),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Sexe')),
                ('nationalite', models.CharField(default='Camerounaise', max_length=100, verbose_name='Nationalité')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email_personnel', models.EmailField(max_length=254, verbose_name='Email personnel')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Cameroun', max_length=100, verbose_name='Pays')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.students.models.etudiant_photo_path, verbose_name='Photo')),
                ('tuteur_nom', models.CharField(max_length=200, verbose_name='Nom du tuteur')),
                ('tuteur_telephone', models.CharField(max_length=20, verbose_name='Téléphone du tuteur')),
                ('tuteur_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du tuteur')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('DIPLOME', 'Diplômé'), ('ABANDONNE', 'Abandon')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'db_table': 'students_etudiants',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_enseignement', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=2, verbose_name="Type d'enseignement")),
                ('volume_horaire_assigne', models.PositiveIntegerField(help_text="Nombre d'heures", verbose_name='Volume horaire assigné')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='academic.anneeacademique', verbose_name='Année académique')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='academic.matiere', verbose_name='Matière')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='students.enseignant', verbose_name='Enseignant')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'db_table': 'students_attributions',
                'ordering': ['annee_academique', 'enseignant'],
                'unique_together': {('enseignant', 'matiere', 'annee_academique', 'type_enseignement')},
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.PositiveIntegerField(help_text='Ex: 1 (L1), 2 (L2), 3 (L3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Niveau')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('montant_inscription', models.DecimalField(decimal_places=2, help_text='En FCFA', max_digits=10, verbose_name="Montant de l'inscription")),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, help_text='En FCFA', max_digits=10, verbose_name='Montant payé')),
                ('statut_paiement', models.CharField(choices=[('COMPLET', 'Paiement complet'), ('PARTIEL', 'Paiement partiel'), ('IMPAYE', 'Impayé')], default='IMPAYE', max_length=20, verbose_name='Statut du paiement')),
                ('statut', models.CharField(choices=[('INSCRIT', 'Inscrit'), ('ABANDONNE', 'Abandon'), ('TRANSFERE', 'Transféré')], default='INSCRIT', max_length=20, verbose_name="Statut de l'inscription")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academic.anneeacademique', verbose_name='Année académique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='students.etudiant', verbose_name='Étudiant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='academic.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'db_table': 'students_inscriptions',
                'ordering': ['-date_inscription'],
                'unique_together': {('etudiant', 'filiere', 'annee_academique')},
            },
        ),
    ]
