# Generated by Django 6.0.1 on 2026-02-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='nationalite',
            field=models.CharField(default='Camerounaise', max_length=100, verbose_name='Nationalité'),
        ),
    ]
