# Generated by Django 6.0.1 on 2026-01-24 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evaluations', '0002_sessiondeliberation_membrejury_decisionjury'),
        ('finance', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('type_document', models.CharField(choices=[('ATTESTATION_SCOLARITE', 'Attestation de scolarité'), ('ATTESTATION_INSCRIPTION', "Attestation d'inscription"), ('ATTESTATION_REUSSITE', 'Attestation de réussite'), ('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('RELEVE_NOTES', 'Relevé de notes'), ('BULLETIN_NOTES', 'Bulletin de notes'), ('BORDEREAU_INSCRIPTION', "Bordereau d'inscription"), ('RECU_PAIEMENT', 'Reçu de paiement'), ('CARTE_ETUDIANT', "Carte d'étudiant")], help_text='Type de document concerné par ce template', max_length=50, unique=True)),
                ('nom', models.CharField(help_text='Nom descriptif du template', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du template')),
                ('contenu_html', models.TextField(help_text='Contenu HTML du template avec variables')),
                ('styles_css', models.TextField(blank=True, help_text='Styles CSS personnalisés')),
                ('entete_html', models.TextField(blank=True, help_text='En-tête HTML (logo, coordonnées université)')),
                ('pied_page_html', models.TextField(blank=True, help_text='Pied de page HTML (signatures, cachets)')),
                ('logo', models.ImageField(blank=True, help_text="Logo de l'université", null=True, upload_to='templates/logos/')),
                ('watermark_texte', models.CharField(blank=True, help_text='Texte du watermark (ex: CONFIDENTIEL, COPIE)', max_length=200)),
                ('actif', models.BooleanField(default=True, help_text='True si ce template est actif')),
            ],
            options={
                'verbose_name': 'Template de document',
                'verbose_name_plural': 'Templates de documents',
                'db_table': 'templates_documents',
                'ordering': ['type_document'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('type_document', models.CharField(choices=[('ATTESTATION_SCOLARITE', 'Attestation de scolarité'), ('ATTESTATION_INSCRIPTION', "Attestation d'inscription"), ('ATTESTATION_REUSSITE', 'Attestation de réussite'), ('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('RELEVE_NOTES', 'Relevé de notes'), ('BULLETIN_NOTES', 'Bulletin de notes'), ('BORDEREAU_INSCRIPTION', "Bordereau d'inscription"), ('RECU_PAIEMENT', 'Reçu de paiement'), ('CARTE_ETUDIANT', "Carte d'étudiant")], help_text='Type de document', max_length=50)),
                ('numero_document', models.CharField(help_text='Numéro unique du document (généré automatiquement)', max_length=100, unique=True)),
                ('fichier', models.FileField(blank=True, help_text='Fichier PDF du document', null=True, upload_to='documents/%Y/%m/')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('GENERE', 'Généré'), ('DELIVRE', 'Délivré'), ('ANNULE', 'Annulé')], default='BROUILLON', help_text='Statut actuel du document', max_length=20)),
                ('date_generation', models.DateTimeField(blank=True, help_text='Date et heure de génération', null=True)),
                ('date_delivrance', models.DateTimeField(blank=True, help_text="Date et heure de délivrance à l'étudiant", null=True)),
                ('qr_code', models.CharField(blank=True, help_text="Code QR pour vérification d'authenticité", max_length=200)),
                ('motif_demande', models.TextField(blank=True, help_text='Motif de la demande du document')),
                ('observations', models.TextField(blank=True, help_text='Observations diverses')),
                ('delivre_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a délivré le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_delivres', to=settings.AUTH_USER_MODEL)),
                ('etudiant', models.ForeignKey(help_text='Étudiant concerné par le document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.etudiant')),
                ('genere_par', models.ForeignKey(help_text='Utilisateur qui a généré le document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_generes', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(blank=True, help_text='Inscription concernée (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='students.inscription')),
                ('paiement', models.ForeignKey(blank=True, help_text='Paiement concerné (pour reçus)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='finance.paiement')),
                ('resultat', models.ForeignKey(blank=True, help_text='Résultat concerné (pour relevés de notes)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='evaluations.resultat')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'documents',
                'ordering': ['-date_generation', '-created_at'],
                'indexes': [models.Index(fields=['numero_document'], name='documents_numero__b04b29_idx'), models.Index(fields=['etudiant', 'type_document'], name='documents_etudian_c5c67b_idx'), models.Index(fields=['statut'], name='documents_statut_e8e372_idx')],
            },
        ),
    ]
