# Generated by Django 6.0.1 on 2026-01-17 18:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: 2024-2025', max_length=20, unique=True, verbose_name='Code')),
                ('date_debut', models.DateField(help_text="Premier jour de l'année académique", verbose_name='Date de début')),
                ('date_fin', models.DateField(help_text="Dernier jour de l'année académique", verbose_name='Date de fin')),
                ('is_active', models.BooleanField(default=False, help_text='Une seule année peut être active à la fois', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Année Académique',
                'verbose_name_plural': 'Années Académiques',
                'db_table': 'academic_annees_academiques',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Faculte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: FST, FDSP, FM', max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Ex: Faculté des Sciences et Techniques', max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('doyen', models.CharField(blank=True, help_text='Nom du doyen de la faculté', max_length=200, verbose_name='Doyen')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Faculté',
                'verbose_name_plural': 'Facultés',
                'db_table': 'academic_facultes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: INFO, MATH, PHYS', max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text="Ex: Département d'Informatique", max_length=200, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('chef_departement', models.CharField(blank=True, max_length=200, verbose_name='Chef de département')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='academic.faculte', verbose_name='Faculté')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'db_table': 'academic_departements',
                'ordering': ['faculte', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: L3-INFO, M2-MATH', max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Ex: Licence 3 Informatique', max_length=200, verbose_name='Nom')),
                ('cycle', models.CharField(choices=[('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('DUT', 'DUT'), ('BTS', 'BTS')], max_length=20, verbose_name='Cycle')),
                ('duree_annees', models.PositiveIntegerField(default=3, help_text="Nombre d'années d'études", validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Durée (années)')),
                ('frais_inscription', models.DecimalField(decimal_places=2, default=0, help_text='Montant en FCFA', max_digits=10, verbose_name="Frais d'inscription")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filieres', to='academic.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Filière',
                'verbose_name_plural': 'Filières',
                'db_table': 'academic_filieres',
                'ordering': ['departement', 'cycle', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: INFO301, MATH205', max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Ex: Programmation Orientée Objet', max_length=200, verbose_name='Nom')),
                ('coefficient', models.PositiveIntegerField(default=1, help_text='Poids de la matière dans la moyenne', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Coefficient')),
                ('credits', models.PositiveIntegerField(default=3, help_text='Nombre de crédits européens', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Crédits ECTS')),
                ('volume_horaire_cm', models.PositiveIntegerField(default=0, help_text='Cours Magistraux (heures)', verbose_name='Volume horaire CM')),
                ('volume_horaire_td', models.PositiveIntegerField(default=0, help_text='Travaux Dirigés (heures)', verbose_name='Volume horaire TD')),
                ('volume_horaire_tp', models.PositiveIntegerField(default=0, help_text='Travaux Pratiques (heures)', verbose_name='Volume horaire TP')),
                ('semestre', models.IntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], default=1, verbose_name='Semestre')),
                ('is_optionnelle', models.BooleanField(default=False, help_text='La matière est-elle optionnelle ?', verbose_name='Optionnelle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filieres', models.ManyToManyField(related_name='matieres', to='academic.filiere', verbose_name='Filières')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'db_table': 'academic_matieres',
                'ordering': ['semestre', 'nom'],
            },
        ),
    ]
