# Generated by Django 6.0.1 on 2026-01-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: A, B, C, AMPHI', max_length=10, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Ex: Bâtiment A, Amphithéâtre', max_length=200, verbose_name='Nom')),
                ('nombre_etages', models.PositiveIntegerField(default=1, verbose_name="Nombre d'étages")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse/Localisation')),
                ('is_active', models.BooleanField(default=True, help_text='Le bâtiment est-il en service ?', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
                'db_table': 'schedule_batiments',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cours', models.CharField(choices=[('CM', 'Cours Magistral'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques')], max_length=2, verbose_name='Type de cours')),
                ('effectif_prevu', models.PositiveIntegerField(blank=True, help_text="Nombre d'étudiants attendus", null=True, verbose_name='Effectif prévu')),
                ('semestre', models.PositiveIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], verbose_name='Semestre')),
                ('date_debut', models.DateField(blank=True, help_text='Date de début effectif du cours', null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, help_text='Date de fin effectif du cours', null=True, verbose_name='Date de fin')),
                ('is_actif', models.BooleanField(default=True, help_text='Le cours est-il programmé ?', verbose_name='Actif')),
                ('remarques', models.TextField(blank=True, verbose_name='Remarques')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.anneeacademique', verbose_name='Année académique')),
                ('enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='students.enseignant', verbose_name='Enseignant')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.filiere', verbose_name='Filière')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='academic.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'db_table': 'schedule_cours',
                'ordering': ['annee_academique', 'filiere', 'creneau'],
            },
        ),
        migrations.CreateModel(
            name='ConflitSalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conflit', models.CharField(choices=[('SALLE', 'Conflit de salle'), ('ENSEIGNANT', "Conflit d'enseignant"), ('CAPACITE', 'Capacité dépassée')], max_length=20, verbose_name='Type de conflit')),
                ('description', models.TextField(verbose_name='Description du conflit')),
                ('statut', models.CharField(choices=[('DETECTE', 'Détecté'), ('EN_COURS', 'En cours de résolution'), ('RESOLU', 'Résolu'), ('IGNORE', 'Ignoré')], default='DETECTE', max_length=20, verbose_name='Statut')),
                ('date_detection', models.DateTimeField(auto_now_add=True, verbose_name='Date de détection')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('solution_appliquee', models.TextField(blank=True, verbose_name='Solution appliquée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cours1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits_comme_cours1', to='schedule.cours', verbose_name='Premier cours')),
                ('cours2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflits_comme_cours2', to='schedule.cours', verbose_name='Deuxième cours')),
            ],
            options={
                'verbose_name': 'Conflit',
                'verbose_name_plural': 'Conflits',
                'db_table': 'schedule_conflits_salles',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi'), ('DIMANCHE', 'Dimanche')], max_length=10, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('code', models.CharField(help_text='Ex: LUNDI-08H00-10H00', max_length=50, unique=True, verbose_name='Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Créneau horaire',
                'verbose_name_plural': 'Créneaux horaires',
                'db_table': 'schedule_creneaux',
                'ordering': ['jour', 'heure_debut'],
                'unique_together': {('jour', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='creneau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='schedule.creneau', verbose_name='Créneau horaire'),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: A101, AMPHI-A', max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Ex: Salle 101, Amphithéâtre A', max_length=200, verbose_name='Nom')),
                ('type_salle', models.CharField(choices=[('COURS', 'Salle de cours'), ('TD', 'Salle de TD'), ('TP', 'Salle de TP/Labo'), ('AMPHI', 'Amphithéâtre'), ('CONFERENCE', 'Salle de conférence')], default='COURS', max_length=20, verbose_name='Type de salle')),
                ('capacite', models.PositiveIntegerField(help_text='Nombre de places', verbose_name='Capacité')),
                ('etage', models.PositiveIntegerField(default=0, help_text='0 = Rez-de-chaussée', verbose_name='Étage')),
                ('equipements', models.TextField(blank=True, help_text='Ex: Projecteur, Ordinateurs, Tableau interactif', verbose_name='Équipements')),
                ('is_disponible', models.BooleanField(default=True, help_text='La salle est-elle utilisable ?', verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='schedule.batiment', verbose_name='Bâtiment')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'db_table': 'schedule_salles',
                'ordering': ['batiment', 'etage', 'code'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='salle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cours', to='schedule.salle', verbose_name='Salle'),
        ),
    ]
