# Generated by Django 6.0.1 on 2026-01-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('DEVOIR', 'Devoir'), ('EXAMEN', 'Examen'), ('RATTRAPAGE', 'Rattrapage'), ('TD', 'Travaux Dirigés'), ('TP', 'Travaux Pratiques'), ('PROJET', 'Projet')], max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(help_text='Ex: Devoir, Examen final', max_length=100, verbose_name='Nom')),
                ('coefficient_min', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Coefficient minimum')),
                ('coefficient_max', models.DecimalField(decimal_places=2, default=3.0, max_digits=4, verbose_name='Coefficient maximum')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Type d'évaluation",
                'verbose_name_plural': "Types d'évaluations",
                'db_table': 'evaluations_types',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Ex: Devoir 1, Examen final', max_length=200, verbose_name='Titre')),
                ('date', models.DateField(verbose_name="Date de l'évaluation")),
                ('coefficient', models.DecimalField(decimal_places=2, help_text='Coefficient de cette évaluation', max_digits=4, verbose_name='Coefficient')),
                ('note_totale', models.DecimalField(decimal_places=2, default=20, help_text='Ex: 20, 100', max_digits=5, verbose_name='Note totale')),
                ('duree', models.PositiveIntegerField(blank=True, help_text="Durée de l'évaluation en minutes", null=True, verbose_name='Durée (minutes)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.anneeacademique', verbose_name='Année académique')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='academic.matiere', verbose_name='Matière')),
                ('type_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evaluations', to='evaluations.typeevaluation', verbose_name="Type d'évaluation")),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'db_table': 'evaluations_evaluations',
                'ordering': ['-date'],
                'unique_together': {('matiere', 'titre', 'annee_academique')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, help_text="Note de l'étudiant", max_digits=5, null=True, verbose_name='Note obtenue')),
                ('note_sur', models.DecimalField(decimal_places=2, default=20, help_text='Barème (ex: 20, 100)', max_digits=5, verbose_name='Note sur')),
                ('appreciations', models.TextField(blank=True, help_text="Commentaires de l'enseignant", verbose_name='Appréciations')),
                ('absence', models.BooleanField(default=False, help_text="L'étudiant était absent ?", verbose_name='Absent')),
                ('date_saisie', models.DateTimeField(auto_now=True, verbose_name='Date de saisie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='students.etudiant', verbose_name='Étudiant')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='evaluations.evaluation', verbose_name='Évaluation')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'evaluations_notes',
                'ordering': ['-date_saisie'],
                'unique_together': {('evaluation', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, help_text='Moyenne sur 20', max_digits=5, verbose_name='Moyenne générale')),
                ('mention', models.CharField(blank=True, choices=[('PASSABLE', 'Passable'), ('AB', 'Assez Bien'), ('B', 'Bien'), ('TB', 'Très Bien'), ('EXCELLENT', 'Excellent')], max_length=20, verbose_name='Mention')),
                ('statut', models.CharField(choices=[('ADMIS', 'Admis'), ('AJOURNE', 'Ajourné'), ('RATTRAPAGE', 'Rattrapage')], max_length=20, verbose_name='Statut')),
                ('credits_obtenus', models.PositiveIntegerField(default=0, verbose_name='Crédits obtenus')),
                ('rang', models.PositiveIntegerField(blank=True, help_text='Position dans la classe', null=True, verbose_name='Rang/Classement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='academic.anneeacademique', verbose_name='Année académique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='students.etudiant', verbose_name='Étudiant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='academic.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Résultat',
                'verbose_name_plural': 'Résultats',
                'db_table': 'evaluations_resultats',
                'ordering': ['-moyenne_generale'],
                'unique_together': {('etudiant', 'matiere', 'annee_academique')},
            },
        ),
    ]
