# Generated by Django 6.0.1 on 2026-01-18 18:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('evaluations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDeliberation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.PositiveIntegerField(help_text='Ex: 1 (L1), 2 (L2), 3 (L3)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)], verbose_name='Niveau')),
                ('semestre', models.PositiveIntegerField(choices=[(1, 'Semestre 1'), (2, 'Semestre 2')], verbose_name='Semestre')),
                ('date_deliberation', models.DateTimeField(verbose_name='Date et heure de délibération')),
                ('lieu', models.CharField(help_text='Ex: Salle de conférence A', max_length=200, verbose_name='Lieu')),
                ('president_jury', models.CharField(help_text='Nom du président', max_length=200, verbose_name='Président du jury')),
                ('statut', models.CharField(choices=[('PREVUE', 'Prévue'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('VALIDEE', 'Validée')], default='PREVUE', max_length=20, verbose_name='Statut')),
                ('proces_verbal', models.TextField(blank=True, help_text='Compte-rendu de la délibération', verbose_name='Procès-verbal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_deliberation', to='academic.anneeacademique', verbose_name='Année académique')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_deliberation', to='academic.filiere', verbose_name='Filière')),
            ],
            options={
                'verbose_name': 'Session de délibération',
                'verbose_name_plural': 'Sessions de délibération',
                'db_table': 'evaluations_sessions_deliberation',
                'ordering': ['-date_deliberation'],
                'unique_together': {('annee_academique', 'filiere', 'niveau', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRESIDENT', 'Président'), ('MEMBRE', 'Membre'), ('SECRETAIRE', 'Secrétaire')], max_length=20, verbose_name='Rôle')),
                ('present', models.BooleanField(default=True, help_text="L'enseignant était présent à la délibération ?", verbose_name='Présent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_jury', to='students.enseignant', verbose_name='Enseignant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres_jury', to='evaluations.sessiondeliberation', verbose_name='Session de délibération')),
            ],
            options={
                'verbose_name': 'Membre du jury',
                'verbose_name_plural': 'Membres du jury',
                'db_table': 'evaluations_membres_jury',
                'ordering': ['role', 'enseignant'],
                'unique_together': {('session', 'enseignant')},
            },
        ),
        migrations.CreateModel(
            name='DecisionJury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.DecimalField(decimal_places=2, help_text='Moyenne sur 20', max_digits=5, verbose_name='Moyenne générale')),
                ('total_credits_obtenus', models.PositiveIntegerField(verbose_name='Total crédits obtenus')),
                ('total_credits_requis', models.PositiveIntegerField(help_text='Nombre de crédits nécessaires', verbose_name='Total crédits requis')),
                ('decision', models.CharField(choices=[('ADMIS', 'Admis'), ('ADMIS_RESERVE', 'Admis avec réserve'), ('AJOURNE', 'Ajourné'), ('REDOUBLEMENT', 'Redoublement'), ('EXCLUSION', 'Exclusion')], max_length=20, verbose_name='Décision du jury')),
                ('mention', models.CharField(blank=True, choices=[('PASSABLE', 'Passable'), ('AB', 'Assez Bien'), ('B', 'Bien'), ('TB', 'Très Bien'), ('EXCELLENT', 'Excellent')], max_length=20, verbose_name='Mention')),
                ('rang_classe', models.PositiveIntegerField(blank=True, null=True, verbose_name='Rang dans la classe')),
                ('observations', models.TextField(blank=True, help_text='Commentaires du jury', verbose_name='Observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions_jury', to='students.etudiant', verbose_name='Étudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='evaluations.sessiondeliberation', verbose_name='Session de délibération')),
            ],
            options={
                'verbose_name': 'Décision du jury',
                'verbose_name_plural': 'Décisions du jury',
                'db_table': 'evaluations_decisions_jury',
                'ordering': ['-moyenne_generale'],
                'unique_together': {('session', 'etudiant')},
            },
        ),
    ]
