# Generated by Django 6.0.1 on 2026-01-23 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeuillePresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('date_cours', models.DateField(help_text='Date à laquelle le cours a eu lieu')),
                ('heure_debut', models.TimeField(help_text='Heure de début du cours')),
                ('heure_fin', models.TimeField(help_text='Heure de fin du cours')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('FERMEE', 'Fermée'), ('ANNULEE', 'Annulée')], default='OUVERTE', help_text='État actuel de la feuille de présence', max_length=20)),
                ('nombre_presents', models.PositiveIntegerField(default=0, help_text="Nombre d'étudiants présents")),
                ('nombre_absents', models.PositiveIntegerField(default=0, help_text="Nombre d'étudiants absents")),
                ('nombre_retards', models.PositiveIntegerField(default=0, help_text="Nombre d'étudiants en retard")),
                ('observations', models.TextField(blank=True, help_text="Observations de l'enseignant sur le déroulement du cours")),
                ('cours', models.ForeignKey(help_text='Cours concerné par cette feuille de présence', on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_presence', to='schedule.cours')),
            ],
            options={
                'verbose_name': 'Feuille de présence',
                'verbose_name_plural': 'Feuilles de présence',
                'db_table': 'feuilles_presence',
                'ordering': ['-date_cours', '-heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='JustificatifAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('date_debut', models.DateField(help_text="Date de début de la période d'absence")),
                ('date_fin', models.DateField(help_text="Date de fin de la période d'absence")),
                ('type_justificatif', models.CharField(choices=[('MEDICAL', 'Certificat médical'), ('ADMINISTRATIF', 'Document administratif'), ('FAMILIAL', 'Événement familial'), ('AUTRE', 'Autre')], help_text='Type de justificatif', max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', help_text='Statut de validation', max_length=20)),
                ('document', models.FileField(help_text='Document justificatif (PDF, image, etc.)', upload_to='justificatifs/%Y/%m/')),
                ('motif', models.TextField(help_text="Motif de l'absence expliqué par l'étudiant")),
                ('commentaire_validation', models.TextField(blank=True, help_text="Commentaire de l'administrateur lors de la validation/rejet")),
                ('date_soumission', models.DateTimeField(auto_now_add=True, help_text='Date et heure de soumission du justificatif')),
                ('date_traitement', models.DateTimeField(blank=True, help_text='Date et heure de validation/rejet', null=True)),
                ('etudiant', models.ForeignKey(help_text='Étudiant qui a soumis le justificatif', on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='students.etudiant')),
            ],
            options={
                'verbose_name': "Justificatif d'absence",
                'verbose_name_plural': "Justificatifs d'absence",
                'db_table': 'justificatifs_absence',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard')], default='ABSENT', help_text="Statut de présence de l'étudiant", max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, help_text="Heure d'arrivée de l'étudiant (si en retard)", null=True)),
                ('absence_justifiee', models.BooleanField(default=False, help_text="True si l'absence est justifiée")),
                ('remarque', models.TextField(blank=True, help_text="Remarques de l'enseignant sur la présence/absence")),
                ('etudiant', models.ForeignKey(help_text='Étudiant concerné', on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='students.etudiant')),
                ('feuille_presence', models.ForeignKey(help_text='Feuille de présence concernée', on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='attendance.feuillepresence')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'db_table': 'presences',
                'ordering': ['etudiant__user__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='feuillepresence',
            index=models.Index(fields=['date_cours'], name='feuilles_pr_date_co_13ae19_idx'),
        ),
        migrations.AddIndex(
            model_name='feuillepresence',
            index=models.Index(fields=['statut'], name='feuilles_pr_statut_e61b76_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feuillepresence',
            unique_together={('cours', 'date_cours')},
        ),
        migrations.AddIndex(
            model_name='justificatifabsence',
            index=models.Index(fields=['statut'], name='justificati_statut_361d13_idx'),
        ),
        migrations.AddIndex(
            model_name='justificatifabsence',
            index=models.Index(fields=['date_debut', 'date_fin'], name='justificati_date_de_5396dc_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['statut'], name='presences_statut_5a40b7_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['absence_justifiee'], name='presences_absence_1fff1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('feuille_presence', 'etudiant')},
        ),
    ]
