# Generated by Django 6.0.1 on 2026-01-24 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('nom', models.CharField(help_text='Nom du dashboard', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du dashboard')),
                ('type_dashboard', models.CharField(choices=[('GENERAL', 'Général'), ('ACADEMIQUE', 'Académique'), ('FINANCIER', 'Financier'), ('ETUDIANT', 'Étudiant'), ('ENSEIGNANT', 'Enseignant'), ('ADMINISTRATION', 'Administration')], help_text='Type de dashboard', max_length=20)),
                ('partage', models.BooleanField(default=False, help_text='True si le dashboard est partagé')),
                ('configuration', models.JSONField(default=dict, help_text='Configuration du dashboard (widgets, layout, filtres)')),
                ('par_defaut', models.BooleanField(default=False, help_text="True si c'est le dashboard par défaut de l'utilisateur")),
                ('proprietaire', models.ForeignKey(help_text='Propriétaire du dashboard', on_delete=django.db.models.deletion.CASCADE, related_name='dashboards_proprietaire', to=settings.AUTH_USER_MODEL)),
                ('utilisateurs_partages', models.ManyToManyField(blank=True, help_text='Utilisateurs avec qui le dashboard est partagé', related_name='dashboards_partages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'db_table': 'dashboards',
                'ordering': ['nom'],
                'unique_together': {('proprietaire', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('nom', models.CharField(help_text='Nom du KPI', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du KPI')),
                ('code', models.CharField(help_text='Code unique du KPI (ex: TAUX_REUSSITE)', max_length=50, unique=True)),
                ('categorie', models.CharField(choices=[('ACADEMIQUE', 'Académique'), ('FINANCIER', 'Financier'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('PRESENCE', 'Présence'), ('RESSOURCES', 'Ressources')], help_text='Catégorie du KPI', max_length=20)),
                ('type_valeur', models.CharField(choices=[('NOMBRE', 'Nombre'), ('POURCENTAGE', 'Pourcentage'), ('MONTANT', 'Montant'), ('RATIO', 'Ratio')], help_text='Type de valeur', max_length=20)),
                ('valeur', models.DecimalField(decimal_places=2, default=0, help_text='Valeur actuelle du KPI', max_digits=15)),
                ('objectif', models.DecimalField(blank=True, decimal_places=2, help_text='Valeur objectif à atteindre', max_digits=15, null=True)),
                ('date_calcul', models.DateField(help_text='Date de calcul de la valeur')),
                ('actif', models.BooleanField(default=True, help_text='True si le KPI est actif')),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Année académique concernée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='academic.anneeacademique')),
                ('filiere', models.ForeignKey(blank=True, help_text='Filière concernée', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis', to='academic.filiere')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'db_table': 'kpis',
                'ordering': ['categorie', 'nom'],
                'indexes': [models.Index(fields=['code'], name='kpis_code_72e9a1_idx'), models.Index(fields=['categorie'], name='kpis_categor_c169b6_idx'), models.Index(fields=['actif'], name='kpis_actif_20c717_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="Date et heure de création de l'enregistrement", verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date et heure de la dernière modification', verbose_name='Date de modification')),
                ('titre', models.CharField(help_text='Titre du rapport', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du rapport')),
                ('type_rapport', models.CharField(choices=[('ACADEMIQUE', 'Académique'), ('FINANCIER', 'Financier'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('PRESENCE', 'Présence'), ('RESSOURCES', 'Ressources'), ('COMMUNICATIONS', 'Communications'), ('DOCUMENTS', 'Documents'), ('GLOBAL', 'Global')], help_text='Type de rapport', max_length=20)),
                ('format_export', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('JSON', 'JSON')], default='PDF', help_text="Format d'export", max_length=10)),
                ('date_debut', models.DateField(help_text='Date de début de la période couverte')),
                ('date_fin', models.DateField(help_text='Date de fin de la période couverte')),
                ('fichier', models.FileField(blank=True, help_text='Fichier du rapport généré', null=True, upload_to='rapports/%Y/%m/')),
                ('genere', models.BooleanField(default=False, help_text='True si le rapport a été généré')),
                ('date_generation', models.DateTimeField(blank=True, help_text='Date et heure de génération', null=True)),
                ('planifie', models.BooleanField(default=False, help_text='True si le rapport est planifié pour génération automatique')),
                ('frequence', models.CharField(choices=[('UNIQUE', 'Unique'), ('QUOTIDIEN', 'Quotidien'), ('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel'), ('ANNUEL', 'Annuel')], default='UNIQUE', help_text='Fréquence de génération automatique', max_length=20)),
                ('prochaine_execution', models.DateTimeField(blank=True, help_text='Date et heure de la prochaine exécution planifiée', null=True)),
                ('parametres', models.JSONField(blank=True, default=dict, help_text='Paramètres personnalisés du rapport (filtres, options)')),
                ('annee_academique', models.ForeignKey(blank=True, help_text='Année académique concernée (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='academic.anneeacademique')),
                ('filiere', models.ForeignKey(blank=True, help_text='Filière concernée (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports', to='academic.filiere')),
                ('genere_par', models.ForeignKey(blank=True, help_text='Utilisateur qui a généré le rapport', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_generes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'db_table': 'rapports',
                'ordering': ['-date_generation', '-created_at'],
                'indexes': [models.Index(fields=['type_rapport'], name='rapports_type_ra_ab4091_idx'), models.Index(fields=['genere'], name='rapports_genere_7179d7_idx'), models.Index(fields=['planifie'], name='rapports_planifi_b745ce_idx')],
            },
        ),
    ]
